name: musa-550-fall-2022
channels:
  - conda-forge

dependencies:
  - python=3.9
  # - numpy=1.23
  # - pandas=1.4.3
  # - altair=4.2.0
  # - vega=3.6.0
  # - geopandas=0.10.2
  # - shapely=1.8.4
  # - descartes=1.1.0
  # - pyepsg=0.4.0
  # - cartopy=0.20.3
  # - mapclassify=2.4.3
  # - bokeh=2.4.3
  # - hvplot=0.8.1
  # - holoviews=1.15.0
  # - geoviews=1.9.5
  # - param=1.12.2
  - panel=0.13.1
  # - folium=0.14.0
  # - pip
  # - pip:
  #     - carto2gpd==1.0.12
